//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigitallyImported.Components.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DigitallyImported.Components.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.yellow_20k.gif.
        /// </summary>
        internal static string _20kIcon {
            get {
                return ResourceManager.GetString("20kIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.orange_32k.gif.
        /// </summary>
        internal static string _32kIcon {
            get {
                return ResourceManager.GetString("32kIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.orange_96k.gif.
        /// </summary>
        internal static string _96kIcon {
            get {
                return ResourceManager.GetString("96kIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.yellow_aacplus_24k.gif.
        /// </summary>
        internal static string aacIcon {
            get {
                return ResourceManager.GetString("aacIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://di.fm/.
        /// </summary>
        internal static string DI_HomePage {
            get {
                return ResourceManager.GetString("DI.HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://di.fm/aacplus/.
        /// </summary>
        internal static string DI_MediaType_aac {
            get {
                return ResourceManager.GetString("DI.MediaType.aac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.di.fm/reference/codec_aacPlus.php.
        /// </summary>
        internal static string DI_MediaType_aac_About {
            get {
                return ResourceManager.GetString("DI.MediaType.aac.About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://di.fm/mp3/.
        /// </summary>
        internal static string DI_MediaType_mp3 {
            get {
                return ResourceManager.GetString("DI.MediaType.mp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.di.fm/reference/codec_MP3.php.
        /// </summary>
        internal static string DI_MediaType_mp3_About {
            get {
                return ResourceManager.GetString("DI.MediaType.mp3.About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://di.fm/wma/.
        /// </summary>
        internal static string DI_MediaType_wma {
            get {
                return ResourceManager.GetString("DI.MediaType.wma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.di.fm/reference/codec_WindowsMedia.php.
        /// </summary>
        internal static string Di_MediaType_wma_About {
            get {
                return ResourceManager.GetString("Di.MediaType.wma.About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.di.fm/partners/xml/playlists.xml.
        /// </summary>
        internal static string DI_Playlist_Xml {
            get {
                return ResourceManager.GetString("DI.Playlist.Xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.icon_mp3.gif.
        /// </summary>
        internal static string mp3Icon {
            get {
                return ResourceManager.GetString("mp3Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.icon_wm.gif.
        /// </summary>
        internal static string wmpIcon {
            get {
                return ResourceManager.GetString("wmpIcon", resourceCulture);
            }
        }
    }
}
